controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_controller:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50
    position_controller:
      type: "effort_controllers/JointPositionController"
      joints:
        - front_left_hip
        - front_left_knee
        - front_right_hip
        - back_left_hip
        - back_right_hip
      pid_gains:
        front_left_hip: { p: 100.0, i: 0.1, d: 10.0 }
        front_right_hip: { p: 100.0, i: 0.1, d: 10.0 }
        back_left_hip: { p: 100.0, i: 0.1, d: 10.0 }
        back_right_hip: { p: 100.0, i: 0.1, d: 10.0 }