---
# Joint State Publisher
- topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"

# Gazebo Simulation Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/world/quadruped_testbench/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

# Initial Condition Actuator
- ros_topic_name: "/quadruped/initial_condition_force"
  gz_topic_name: "/model/quadruped/joint/z_trans_x_trans_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FR Leg Controllers
- ros_topic_name: "/quadruped/cmd/FR_hip_joint"
  gz_topic_name: "/model/quadruped/joint/FR_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/FR_thigh_joint"
  gz_topic_name: "/model/quadruped/joint/FR_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/FR_calf_joint"
  gz_topic_name: "/model/quadruped/joint/FR_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FL Leg Controllers
- ros_topic_name: "/quadruped/cmd/FL_hip_joint"
  gz_topic_name: "/model/quadruped/joint/FL_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/FL_thigh_joint"
  gz_topic_name: "/model/quadruped/joint/FL_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/FL_calf_joint"
  gz_topic_name: "/model/quadruped/joint/FL_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RL Leg Controllers
- ros_topic_name: "/quadruped/cmd/RL_hip_joint"
  gz_topic_name: "/model/quadruped/joint/RL_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/RL_thigh_joint"
  gz_topic_name: "/model/quadruped/joint/RL_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/RL_calf_joint"
  gz_topic_name: "/model/quadruped/joint/RL_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RR Leg Controllers
- ros_topic_name: "/quadruped/cmd/RR_hip_joint"
  gz_topic_name: "/model/quadruped/joint/RR_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/RR_thigh_joint"
  gz_topic_name: "/model/quadruped/joint/RR_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd/RR_calf_joint"
  gz_topic_name: "/model/quadruped/joint/RR_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"