---
# Joint State Publisher
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"

# FR Leg Controllers
- ros_topic_name: "/quadruped/cmd_FR_hip_joint"
  gz_topic_name: "/quadruped/cmd_FR_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_FR_thigh_joint"
  gz_topic_name: "/quadruped/cmd_FR_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_FR_calf_joint"
  gz_topic_name: "/quadruped/cmd_FR_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FL Leg Controllers
- ros_topic_name: "/quadruped/cmd_FL_hip_joint"
  gz_topic_name: "/quadruped/cmd_FL_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_FL_thigh_joint"
  gz_topic_name: "/quadruped/cmd_FL_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_FL_calf_joint"
  gz_topic_name: "/quadruped/cmd_FL_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RL Leg Controllers
- ros_topic_name: "/quadruped/cmd_RL_hip_joint"
  gz_topic_name: "/quadruped/cmd_RL_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_RL_thigh_joint"
  gz_topic_name: "/quadruped/cmd_RL_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_RL_calf_joint"
  gz_topic_name: "/quadruped/cmd_RL_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RR Leg Controllers
- ros_topic_name: "/quadruped/cmd_RR_hip_joint"
  gz_topic_name: "/quadruped/cmd_RR_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_RR_thigh_joint"
  gz_topic_name: "/quadruped/cmd_RR_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/quadruped/cmd_RR_calf_joint"
  gz_topic_name: "/quadruped/cmd_RR_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"