---
# Joint State Publisher
- topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"

# Gazebo Simulation Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/world/quadruped_testbench/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

# Initial Condition Actuator
- ros_topic_name: "/quadruped/initial_condition_force"
  gz_topic_name: "/model/quadruped/joint/z_trans_x_trans_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FR Leg Controllers
- topic_name: "/quadruped/cmd_FR_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_FR_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_FR_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FL Leg Controllers
- topic_name: "/quadruped/cmd_FL_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_FL_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_FL_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RL Leg Controllers
- topic_name: "/quadruped/cmd_RL_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_RL_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_RL_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# RR Leg Controllers
- topic_name: "/quadruped/cmd_RR_hip_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_RR_thigh_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"
- topic_name: "/quadruped/cmd_RR_calf_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"

# FR Joint Torques
- topic_name: "/quadruped/FR_hip_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/FR_thigh_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/FR_calf_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"

# FL Joint Torques
- topic_name: "/quadruped/FL_hip_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/FL_thigh_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/FL_calf_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"

# RL Joint Torques
- topic_name: "/quadruped/RL_hip_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/RL_thigh_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/RL_calf_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"

# RR Joint Torques
- topic_name: "/quadruped/RR_hip_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/RR_thigh_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
- topic_name: "/quadruped/RR_calf_joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"
