# This is the single source of truth for all information on the quadrupedal parameters

# Note: By default, inertial values will be calculated based off of uniform mass distribution
# assumptions if no value is provided. If values are provided for the inertial tensor, those values
# will override the default.

# The framing of the base follows the guidelines of REP-103 (https://www.ros.org/reps/rep-0103.html)
# x-direction = forward
# y-direction = left
# z-direction = up

# Legs are mounted to the corners of the base by default.
# The hips rotates about axes parallel to the body x-axis which
# passes thorough the right and right sides of the body respectivley.
# The legs are modeled as kinematic chains of cylindrical bodies, analagous to a 
# planar 2-link manipulator which can rotate into the 3rd dimension

# Base: Rectangular prisum with dimensions Lx, Ly, Lz, and mass m
base:
  Lx: 3 # Length - x direction
  Ly: 2 # Length - y direction
  Lz: 1 # Length - z direction
  m: 1 # Total mass of body
  I:
    Ixx: # (mass / 12) * (L_y*L_y + L_z*L_z)
    Iyy: # (mass / 12) * (L_x*L_x + L_z*L_z)
    Izz: # (mass / 12) * (L_x*L_x + L_y*L_y)

# Front Right Leg
FR:
  rad: 0.1 # Radius of cylindrical leg links
  L1: 0.25 # Length - hip link
  L2: 1 # Length - thigh link
  L3: 1 # Length - calf link
  m1: 1 # Mass - hip link
  I1: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass
  
  m2: 1 # Mass - thigh link
  I2: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m3: 1 # Mass - calf link
  I3: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m4: 1 # Mass - foot link
  I4: # Commented value is uniform distribution inertia
    Ixx: # (2/5) * (mass*rad*rad)
    Iyy: # (83/320) * (mass*rad*rad)
    Izz: # (83/320) * (mass*rad*rad)

# Front Left Leg
FL:
  rad: 0.1 # Radius of cylindrical leg links
  L1: 0.25 # Length - hip link
  L2: 1 # Length - thigh link
  L3: 1 # Length - calf link
  m1: 1 # Mass - hip link
  I1: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass
  
  m2: 1 # Mass - thigh link
  I2: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m3: 1 # Mass - calf link
  I3: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m4: 1 # Mass - foot link
  I4: # Commented value is uniform distribution inertia
    Ixx: # (2/5) * (mass*rad*rad)
    Iyy: # (83/320) * (mass*rad*rad)
    Izz: # (83/320) * (mass*rad*rad)

# Rear Left Leg
RL:
  rad: 0.1 # Radius of cylindrical leg links
  L1: 0.25 # Length - hip link
  L2: 1 # Length - thigh link
  L3: 1 # Length - calf link
  m1: 1 # Mass - hip link
  I1: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass
  
  m2: 1 # Mass - thigh link
  I2: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m3: 1 # Mass - calf link
  I3: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m4: 1 # Mass - foot link
  I4: # Commented value is uniform distribution inertia
    Ixx: # (2/5) * (mass*rad*rad)
    Iyy: # (83/320) * (mass*rad*rad)
    Izz: # (83/320) * (mass*rad*rad)

# Rear Right Leg
RR:
  rad: 0.1 # Radius of cylindrical leg links
  L1: 0.25 # Length - hip link
  L2: 1 # Length - thigh link
  L3: 1 # Length - calf link
  m1: 1 # Mass - hip link
  I1: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass
  
  m2: 1 # Mass - thigh link
  I2: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m3: 1 # Mass - calf link
  I3: # Commented value is uniform distribution inertia
    Ixx: # (1/2) * mass * rad*rad
    Iyy: # (1/12) * (length*length + 3*rad*rad) * mass
    Izz: # (1/12) * (length*length + 3*rad*rad) * mass

  m4: 1 # Mass - foot link
  I4: # Commented value is uniform distribution inertia
    Ixx: # (2/5) * (mass*rad*rad)
    Iyy: # (83/320) * (mass*rad*rad)
    Izz: # (83/320) * (mass*rad*rad)
