controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #   joints:
    #     - front_left_hip
    #     - front_left_knee
    #     - front_right_hip
    #     - front_right_knee
    #     - rear_left_hip
    #     - rear_left_knee
    #     - rear_right_hip
    #     - rear_right_knee
    #   gains:
    #     front_left_hip: {p: 100.0, d: 10.0, i: 1.0}
    #     # Add similar gain configurations for other joints