---
# Gazebo Simulation Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/world/quadruped_testbench/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

# Joint torque publisher
- topic_name: "/joint_torque"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "GZ_TO_ROS"

- topic_name: "/cmd_pendulum_joint"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: "ROS_TO_GZ"