<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include
        filename="/workspace/src/robot_descriptions/generic_quadruped_description/xacro/const.xacro" />

    <xacro:macro name="hip_joint" params="leg_name right Px Py Pz">
        <joint name="${leg_name}_hip_joint" type="continuous">
            <parent link="base" />
            <child link="${leg_name}_hip" />
            <axis xyz="0 0 1" />

            <xacro:if value="${right == True}">
                <origin
                    xyz="${Px} ${Py} ${Pz}"
                    rpy="${PI/2} 0.0 ${-PI/2}" />
            </xacro:if>

            <xacro:if value="${right == False}">
                <origin
                    xyz="${Px} ${Py} ${Pz}"
                    rpy="${PI/2} 0.0 ${PI/2}" />
            </xacro:if>
        </joint>
    </xacro:macro>

    <xacro:macro name="thigh_joint" params="leg_name right length">
        <joint name="${leg_name}_thigh_joint" type="continuous">
            <parent link="${leg_name}_hip" />
            <child link="${leg_name}_thigh" />
            <axis xyz="0 0 1" />

            <xacro:if value="${right == True}">
                <origin
                    xyz="${length} 0 0"
                    rpy="${PI/2} 0.0 ${-PI/2}" />
            </xacro:if>

            <xacro:if value="${right == False}">
                <origin
                    xyz="${length} 0 0"
                    rpy="${-PI/2} 0 ${-PI/2}" />
            </xacro:if>
        </joint>
    </xacro:macro>

    <xacro:macro name="calf_joint" params="leg_name right length">
        <joint name="${leg_name}_calf_joint" type="continuous">
            <parent link="${leg_name}_thigh" />
            <child link="${leg_name}_calf" />
            <axis xyz="0 0 1" />

            <xacro:if value="${right == True}">
                <origin
                    xyz="${length} 0 0"
                    rpy="0.0 0.0 0.0" />
            </xacro:if>

            <xacro:if value="${right == False}">
                <origin
                    xyz="${length} 0 0"
                    rpy="0.0 0.0 0.0" />
            </xacro:if>
        </joint>
    </xacro:macro>

    <xacro:macro name="fixed_joint" params="name parent child length">
        <joint name="${name}" type="fixed">
            <origin
                xyz="${length} 0 0"
                rpy="0.0 0.0 0.0" />
            <parent
                link="${parent}" />
            <child
                link="${child}" />
        </joint>
    </xacro:macro>

    <xacro:macro name="base_link" params="name L_x L_y L_z mass inertial_link">
        <link name="${name}">
            <xacro:if value="${inertial_link == True}">
                <inertial>
                    <origin
                        xyz="0 0 0"
                        rpy="0 0 0" />
                    <mass
                        value="${mass}" />
                    <inertia
                        ixx="${(mass / 12) * (L_y*L_y + L_z*L_z)}"
                        ixy="0"
                        ixz="0"
                        iyy="${(mass / 12) * (L_x*L_x + L_z*L_z)}"
                        iyz="0"
                        izz="${(mass / 12) * (L_x*L_x + L_y*L_y)}" />
                </inertial>
            </xacro:if>
            <xacro:if value="${inertial_link == False}">
                <visual>
                    <origin
                        xyz="0 0 0"
                        rpy="0 0 0" />
                    <geometry>
                        <box size="${L_x} ${L_y} ${L_z}" />
                    </geometry>
                    <material name="red" />
                </visual>
            </xacro:if>
            <xacro:no_collision />
        </link>
    </xacro:macro>

    <xacro:macro name="link" params="link_name mass rad length">
        <link name="${link_name}">
            <inertial>
                <origin
                    xyz="${length/2} 0 0"
                    rpy="0 0 0" />
                <mass value="${mass}" />
                <inertia
                    ixx="${.5 * mass * rad*rad}"
                    ixy="0"
                    ixz="0"
                    iyy="${(1/12) * (length*length + 3*rad*rad) * mass}"
                    iyz="0"
                    izz="${(1/12) * (length*length + 3*rad*rad) * mass}" />
            </inertial>
            <visual>
                <origin
                    xyz="${length/2} 0 0"
                    rpy="0 ${PI/2} 0" />
                <geometry>
                    <cylinder length="${length}" radius="${rad}" />
                </geometry>
                <material name="grey" />
            </visual>
            <xacro:no_collision />
        </link>
    </xacro:macro>

    <xacro:macro name="foot" params="foot_name mass rad">
        <link name="${foot_name}">
            <inertial>
                <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
                <mass value="${mass}" />
                <inertia
                    ixx="${(2/5) * (mass*rad*rad)}"
                    ixy="0"
                    ixz="0"
                    iyy="${(83/320) * (mass*rad*rad)}"
                    iyz="0"
                    izz="${(83/320) * (mass*rad*rad)}" />
            </inertial>
            <visual>
                <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
                <geometry>
                    <sphere radius="${rad}" />
                </geometry>
                <material name="red" />
            </visual>
            <collision>
                <origin
                    xyz="0 0 0"
                    rpy="0 0 0" />
                <geometry>
                    <sphere radius="${rad}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="no_collision">
        <collision>
            <geometry>
                <box size="0 0 0" />
            </geometry>
        </collision>
    </xacro:macro>

    <xacro:macro name="leg" params="leg_name right Px Py Pz rad L1 L2 L3 m1 m2 m3 m4">

        <xacro:link link_name="${leg_name}_hip" mass="${m1}" rad="${rad}" length="${L1}" />

        <xacro:hip_joint leg_name="${leg_name}" right="${right}" Px="${Px}" Py="${Py}" Pz="${Pz}" />

        <xacro:link link_name="${leg_name}_thigh" mass="${m2}" rad="${rad}" length="${L2}" />

        <xacro:thigh_joint leg_name="${leg_name}" right="${right}" length="${L1}" />

        <xacro:link link_name="${leg_name}_calf" mass="${m3}" rad="${rad}" length="${L3}" />

        <!-- foot sphere at knee position for contact purposes -->
        <xacro:foot foot_name="${leg_name}_knee" mass="0.0" rad="${rad}" />

        <xacro:fixed_joint name="${leg_name}_knee_joint" parent="${leg_name}_calf"
            child="${leg_name}_knee" length="0.0" />

        <xacro:calf_joint leg_name="${leg_name}" right="${right}" length="${L2}" />

        <xacro:foot foot_name="${leg_name}_foot" mass="${m4}" rad="${rad}" />

        <xacro:fixed_joint name="${leg_name}_foot_joint" parent="${leg_name}_calf"
            child="${leg_name}_foot" length="${L3}" />

    </xacro:macro>
</robot>